### ISSUE TITLE
Random disconnects following "critical exception handling a packet on channel aunis"

### ISSUE THREAD

**Issue by NovaXeros** [MrJake222/AUNIS#143]
Myself and the players of my small private server are experiencing disconnects from the server with the following message displayed on the client:

"Network Disconnect: A fatal error has occurred, this connection is terminated"

Just before the disconnect occurs, the latest.log shows this as having occurred:

`[21:14:14] [Netty Epoll Server IO #4/ERROR] [FML]: There was a critical exception handling a packet on channel aunis
java.lang.RuntimeException: PLAYER target expects a Player arg
	at net.minecraftforge.fml.common.network.FMLOutboundHandler$OutboundTarget$4.validateArgs(FMLOutboundHandler.java:136) ~[FMLOutboundHandler$OutboundTarget$4.class:?]
	at net.minecraftforge.fml.common.network.FMLOutboundHandler.write(FMLOutboundHandler.java:367) ~[FMLOutboundHandler.class:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[minecraft_server.1.12.2.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730) ~[minecraft_server.1.12.2.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816) ~[minecraft_server.1.12.2.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723) ~[minecraft_server.1.12.2.jar:?]
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:111) ~[minecraft_server.1.12.2.jar:?]
	at io.netty.handler.codec.MessageToMessageCodec.write(MessageToMessageCodec.java:116) ~[minecraft_server.1.12.2.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[minecraft_server.1.12.2.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801) ~[minecraft_server.1.12.2.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814) ~[minecraft_server.1.12.2.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794) ~[minecraft_server.1.12.2.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831) ~[minecraft_server.1.12.2.jar:?]
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1032) ~[minecraft_server.1.12.2.jar:?]
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:296) ~[minecraft_server.1.12.2.jar:?]
	at net.minecraftforge.fml.common.network.simpleimpl.SimpleNetworkWrapper.sendTo(SimpleNetworkWrapper.java:250) ~[SimpleNetworkWrapper.class:?]
	at mrjake.aunis.packet.PositionedPlayerPacket.respond(PositionedPlayerPacket.java:34) ~[PositionedPlayerPacket.class:?]
	at mrjake.aunis.packet.StateUpdateRequestToServer$StateUpdateServerHandler.lambda$onMessage$0(StateUpdateRequestToServer.java:58) ~[StateUpdateRequestToServer$StateUpdateServerHandler.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_242]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_242]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) ~[MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) ~[nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) ~[MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
[21:14:14] [Netty Epoll Server IO #4/ERROR] [FML]: Network Disconnect: A fatal error has occurred, this connection is terminated
`

As yet I've been unable to reliably reproduce the error - there hasn't been any particular action causes it to happen, it appears to just happen randomly and it seems to be getting worse (only affected one player, now affects myself and 2 others).

Please let me know if you need the full logs/any other information and I'll be happy to provide

**Comment by NovaXeros** [comment]
[2020-04-19-1.log.gz](https://github.com/MrJake222/AUNIS/files/4502873/2020-04-19-1.log.gz)

Log file attached from yesterday where you can see a few successful dials, everything working nicely, and then suddenly the server gets absolutely battered by the above error.

**Comment by PoltixeTheDerg** [comment]
I am unable to replicate your issue. Try replicating the bug with the minimum required mods for AUNIS to run, if you cannot, add mods back until the error occurs, once you know what mod is causing the error, please say here it will help with debugging a ton.

**Comment by NovaXeros** [comment]
Unfortunately the error is incredibly hard to replicate as it is seemingly random in nature and therefore cannot be invoked.

We went an entire day yesterday without the error appearing once, with absolutely nothing changed on the server/modpack. Other days we can get absolutely hammered by it.

I'm wondering if the bug isn't an incompatibility with another mod but is instead related to server lag/latency? Spitballing here, but maybe the 'fatal error' isn't BECAUSE of the aunis error, but rather happens in concurrency, ie.:

Player 1 begins to lose connection
Server no longer has player object instance
Aunis asks for Player 1 packet update, gets error because Player object no longer exists
Server displays fatal error

I'll take another walk through the full server logs to see if I can ascertain any more information and I'll keep my eyes open for the error reoccuring, but I'm hesitant to start removing mods as this is both a live multiplayer server with a large number of mods and is also random in nature, so who knows how long I'd have to impact my players by altering the mod set.

**Comment by PoltixeTheDerg** [comment]
Can I get a copy of your mods and config folder so I can try to get this happening on a controlled server?

**Comment by MrJake222** [comment]
Okay so I've moved this one to Forge's system. Feel free to reopen If bug reoccurs(or create a new one)
