### ISSUE TITLE
Server crash caused by gates in galacticraft space station dimension 

### ISSUE THREAD

**Issue by YETIMAN2020** [MrJake222/AUNIS#148]
when starting the server with gates in the galcticraft space station dimension the server will loop an error.

	at net.minecraft.world.World.func_72964_e(World.java:310) ~[amu.class:?]
	at net.minecraft.world.World.func_175726_f(World.java:305) ~[amu.class:?]
	at net.minecraft.world.World.func_180495_p(World.java:911) ~[amu.class:?]
	at net.minecraft.tileentity.TileEntity.func_70296_d(TileEntity.java:157) ~[avj.class:?]
	at mrjake.aunis.tileentity.stargate.StargateClassicBaseTile.updatePowerTier(StargateClassicBaseTile.java:696) ~[StargateClassicBaseTile.class:?]
	at mrjake.aunis.tileentity.stargate.StargateClassicBaseTile.func_145839_a(StargateClassicBaseTile.java:276) ~[StargateClassicBaseTile.class:?]
	at mrjake.aunis.tileentity.stargate.StargateMilkyWayBaseTile.func_145839_a(StargateMilkyWayBaseTile.java:241) ~[StargateMilkyWayBaseTile.class:?]
	at net.minecraft.tileentity.TileEntity.func_190200_a(TileEntity.java:120) ~[avj.class:?]
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.loadEntities(AnvilChunkLoader.java:495) ~[aye.class:?]
	at net.minecraftforge.common.chunkio.ChunkIOProvider.syncCallback(ChunkIOProvider.java:101) ~[ChunkIOProvider.class:?]
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:94) ~[ChunkIOExecutor.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:118) ~[on.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_186028_c(ChunkProviderServer.java:89) ~[on.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:135) ~[on.class:?]
	at net.minecraft.world.World.func_72964_e(World.java:310) ~[amu.class:?]
	at net.minecraft.world.World.func_175726_f(World.java:305) ~[amu.class:?]
	at net.minecraft.world.World.func_180495_p(World.java:911) ~[amu.class:?]
	at net.minecraft.tileentity.TileEntity.func_70296_d(TileEntity.java:157) ~[avj.class:?]
	at mrjake.aunis.tileentity.stargate.StargateClassicBaseTile.updatePowerTier(StargateClassicBaseTile.java:696) ~[StargateClassicBaseTile.class:?]
	at mrjake.aunis.tileentity.stargate.StargateClassicBaseTile.func_145839_a(StargateClassicBaseTile.java:276) ~[StargateClassicBaseTile.class:?]
	at mrjake.aunis.tileentity.stargate.StargateMilkyWayBaseTile.func_145839_a(StargateMilkyWayBaseTile.java:241) ~[StargateMilkyWayBaseTile.class:?]
	at net.minecraft.tileentity.TileEntity.func_190200_a(TileEntity.java:120) ~[avj.class:?]
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.loadEntities(AnvilChunkLoader.java:495) ~[aye.class:?]
	at net.minecraftforge.common.chunkio.ChunkIOProvider.syncCallback(ChunkIOProvider.java:101) ~[ChunkIOProvider.class:?]

if the dimension is removed the server starts fine. any help would be great.
[latest.log](https://github.com/MrJake222/AUNIS/files/4528552/latest.log)

**Comment by MrJake222** [comment]
Fixed by 9a8da631104f5c93fe954a888500d3896e65ee7d, I think
