### ISSUE TITLE
disconnect from the server while holding univers dialer and impossible to reconnect

### ISSUE THREAD

**Issue by FlynCZE** [MrJake222/AUNIS#242]
This was written to the server console from my connection to my kick

```
[19:50:06] [Server thread/INFO] [minecraft/PlayerList]: FlynCZE[/89.203.217.72:64030] logged in with entity id 250482 at (-85.93853632614025, 68.0, -16.216694790571964)
[19:50:06] [Server thread/INFO] [minecraft/DedicatedServer]: FlynCZE joined the game
[19:50:06] [Server thread/INFO] [EnderCore]: Sending server configs to client for com.enderio.core.common.config.ConfigHandler
[19:50:06] [Server thread/INFO] [Mekanism]: Sent config to 'FlynCZE.'
[19:50:06] [Server thread/WARN] [enderio]: @Devs: See github for dev env setup; set INDEV if needed.
[19:50:06] [Server thread/INFO] [STDOUT]: [net.minecraft.crash.CrashReport:func_85057_a:300]: Negative index in crash report handler (0/10)
[19:50:06] [Server thread/WARN] [minecraft/NetworkSystem]: Failed to handle packet for /89.203.217.72:64030
net.minecraft.util.ReportedException: Ticking player
at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:459) ~[oq.class:?]
at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:173) ~[pa.class:?]
at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209) ~[NetworkDispatcher$1.class:?]
at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285) ~[gw.class:?]
at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180) [oz.class:?]
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:790) [MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_261]
Caused by: java.lang.NullPointerException
[19:50:07] [Server thread/WARN] [enderio]: @Devs: See github for dev env setup; set INDEV if needed.
[19:50:07] [Server thread/INFO] [STDOUT]: [net.minecraft.crash.CrashReport:func_85057_a:300]: Negative index in crash report handler (0/10)
[19:50:07] [Server thread/WARN] [minecraft/NetworkSystem]: Failed to handle packet for /89.203.217.72:64030
net.minecraft.util.ReportedException: Ticking player
at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:459) ~[oq.class:?]
at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:173) ~[pa.class:?]
at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209) ~[NetworkDispatcher$1.class:?]
at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285) ~[gw.class:?]
at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180) [oz.class:?]
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:790) [MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_261]
Caused by: java.lang.NullPointerException
[19:50:08] [Server thread/WARN] [enderio]: @Devs: See github for dev env setup; set INDEV if needed.
[19:50:08] [Server thread/INFO] [STDOUT]: [net.minecraft.crash.CrashReport:func_85057_a:300]: Negative index in crash report handler (0/10)
[19:50:08] [Server thread/WARN] [minecraft/NetworkSystem]: Failed to handle packet for /89.203.217.72:64030
net.minecraft.util.ReportedException: Ticking player
at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:459) ~[oq.class:?]
at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:173) ~[pa.class:?]
at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209) ~[NetworkDispatcher$1.class:?]
at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285) ~[gw.class:?]
at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180) [oz.class:?]
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:790) [MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_261]
Caused by: java.lang.NullPointerException
[19:50:09] [Server thread/WARN] [enderio]: @Devs: See github for dev env setup; set INDEV if needed.
[19:50:09] [Server thread/INFO] [STDOUT]: [net.minecraft.crash.CrashReport:func_85057_a:300]: Negative index in crash report handler (0/10)
[19:50:09] [Server thread/WARN] [minecraft/NetworkSystem]: Failed to handle packet for /89.203.217.72:64030
net.minecraft.util.ReportedException: Ticking player
at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:459) ~[oq.class:?]
at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:173) ~[pa.class:?]
at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209) ~[NetworkDispatcher$1.class:?]
at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285) ~[gw.class:?]
at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180) [oz.class:?]
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:790) [MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_261]
Caused by: java.lang.NullPointerException
[19:50:10] [Server thread/WARN] [enderio]: @Devs: See github for dev env setup; set INDEV if needed.
[19:50:10] [Server thread/INFO] [STDOUT]: [net.minecraft.crash.CrashReport:func_85057_a:300]: Negative index in crash report handler (0/10)
[19:50:10] [Server thread/WARN] [minecraft/NetworkSystem]: Failed to handle packet for /89.203.217.72:64030
net.minecraft.util.ReportedException: Ticking player
at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:459) ~[oq.class:?]
at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:173) ~[pa.class:?]
at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209) ~[NetworkDispatcher$1.class:?]
at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285) ~[gw.class:?]
at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180) [oz.class:?]
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:790) [MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_261]
Caused by: java.lang.NullPointerException
[19:50:10] [Server thread/INFO] [minecraft/NetHandlerPlayServer]: FlynCZE lost connection: Internal server error
[19:50:10] [Server thread/INFO] [minecraft/DedicatedServer]: FlynCZE left the game



and this was written to the server console when the uverse dialer is picked up


[20:16:16] [Server thread/WARN] [aunis]: Facing down when activating DHD
[20:16:16] [Server thread/WARN] [aunis]: Facing down when activating DHD
[20:16:19] [Server thread/WARN] [aunis]: Facing down when activating DHD
[20:16:19] [Server thread/WARN] [aunis]: Facing down when activating DHD
```

**Comment by MrJake222** [comment]
Why do you think it's related to Aunis?

**Comment by FlynCZE** [comment]
Thanks for answer
Because when I holding universe dialer it kicks me from the server and I can't reconnect

**Comment by MrJake222** [comment]
It doesn't give me the reason why a `java.lang.NullPointerException` occurred... Can you upload a full log? Possibly also a client one?

**Comment by FlynCZE** [comment]
Yes of course here it is 
[2020-11-04-7.log SERVER.gz](https://github.com/MrJake222/AUNIS/files/5492808/2020-11-04-7.log.SERVER.gz)
[2020-11-04-7.log CLIENT.gz](https://github.com/MrJake222/AUNIS/files/5492809/2020-11-04-7.log.CLIENT.gz)

**Comment by NextLight** [comment]
I'm having the same issue (and I think #241 as well).
The only interesting log lines are:
```
Caused by: java.lang.NullPointerException
at mrjake.aunis.item.dialer.UniverseDialerItem.onUpdate(UniverseDialerItem.java:118) ~[UniverseDialerItem.class:?]
```

Line 118 is
```java
UniverseDialerMode mode = UniverseDialerMode.valueOf(compound.getByte("mode"));
```
so I guess that the issue is that (for some reason) compound is null.

**Comment by oddrobbia** [comment]
i think the game trying to reading the universe dialer data because have more option as item as the game can handle i got sometimes the crash report player inventory detection error thing

**Comment by NightcoreIsla** [comment]
i also got this problem on OceanOutlast modpack
if anyone taking univers dialer and shift + right click
then he will be disconnect on server by networkmanager(log said) untill delete the playerdata inventory's universdialer item nbt,or player drop the universdialer at the moment between login and disconnect,about 0.1s
and the console will keep print "[Aunis]: Facing down when activating DHD" every second
