### ISSUE TITLE
Orlin gate drops is not working

### ISSUE THREAD

**Issue by zendiik** [MrJake222/AUNIS#271]
After breaking the Orlin Gate Ring Blocks, this error pops up.

Version: `1.9.12-alpha-2021-01-14`

```
java.util.concurrent.ExecutionException: java.lang.NullPointerException
    at java.util.concurrent.FutureTask.report(Unknown Source)
    at java.util.concurrent.FutureTask.get(Unknown Source)
    at net.minecraft.util.Util.runTask(Util.java:531)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:723)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:279)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
    at mrjake.aunis.block.stargate.StargateOrlinMemberBlock.getDrops(StargateOrlinMemberBlock.java:105)
    at net.minecraft.block.Block.getDrops(Block.java:1300)
    at net.minecraft.block.Block.dropBlockAsItemWithChance(Block.java:571)
    at net.minecraft.block.Block.dropBlockAsItem(Block.java:564)
    at net.minecraft.block.Block.harvestBlock(Block.java:735)
    at net.minecraft.server.management.PlayerInteractionManager.tryHarvestBlock(PlayerInteractionManager.java:327)
    at net.minecraft.server.management.PlayerInteractionManager.blockRemoving(PlayerInteractionManager.java:244)
    at net.minecraft.network.NetHandlerPlayServer.processPlayerDigging(NetHandlerPlayServer.java:704)
    at net.minecraft.network.play.client.CPacketPlayerDigging.processPacket(SourceFile:40)
    at net.minecraft.network.play.client.CPacketPlayerDigging.processPacket(SourceFile:10)
    at net.minecraft.network.PacketThreadUtil$1.run(PacketThreadUtil.java:22)
    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
    at java.util.concurrent.FutureTask.run(Unknown Source)
    at net.minecraft.util.Util.runTask(Util.java:529)
```

**Comment by slava110** [comment]
Weird bug. What forge version are you using?

**Comment by zendiik** [comment]
14.23.5.2855
